import type { ShapeActivity } from "./shape-runs";

// Snapshot of mapped Shape runs from 2026-08-14. Used when the API
// is unreachable, the key is missing, or the live payload is empty.
export const FALLBACK_SHAPE_ACTIVITIES: ShapeActivity[] = [
  {
    id: "a075f8a8-9a44-4829-952e-ed815384741f",
    date: "2026-08-14T05:16:21.000Z",
    title: "Tempo 2km",
    sportType: "run",
    distance: 4645.6,
    duration: 1528,
    speed: 3.04,
    heartRate: 167.9,
    elevationGain: 25.9,
    completed: true,
    source: "strava",
    externalId: "19734950528",
    map: "eoijF~k`v@XC`@KNAFE`BONIR?BBDAXORAHEl@Kt@Gj@KJIT?BALAb@KtBYp@CFE^Ad@Iv@Gt@CdA@NEf@@h@AHBLEL@JCh@GT@h@EXKPCH?r@[f@IFGbA]JGLER@b@IH?^GX?TIJ@TELE^GvA_@hB[XI^C\\Kf@ATGx@AREBG@IAKIOGq@?a@Kg@Ce@G[@GAW@OEa@?WIiABWGOAeACI@UEMECE?KDS@KDy@V]Hs@VIBuAf@k@Ns@H{ADa@BMFa@AMBk@@MDOAYDY?QBc@?oAHWCmAH]LSA_@P]Fm@PcARmAJaANMASFS?KDKAYF]@KDY@WFcAHc@Fc@@OFKAe@FYAQBm@?c@@w@A[De@Ey@?O@cA[SKQCeBk@SCIGaA[W?YHSTqBlA{BzAOPAHAFHh@AP@h@DTHbBDZDf@DP@RBH@j@Hd@?ZXvC@r@DNPhB?j@DLBl@DV@XV|BJ`CKJg@Hg@TI?k@Tq@N_@LCDW?CAGM?c@Gw@SaBKk@Gm@K[Iq@GQGe@Oq@OuAOs@Ca@_@qBIWKgAEKC[Mm@C]@U^["
  },
  {
    id: "a46ca83e-8bf1-4a67-bf8a-aea7e4e43d9e",
    date: "2026-08-12T05:42:09.000Z",
    title: "Mile Repeats",
    sportType: "run",
    distance: 7429.8,
    duration: 2501,
    speed: 2.971,
    heartRate: 167,
    elevationGain: 42.2,
    completed: true,
    source: "strava",
    externalId: "19706777453",
    map: "kjijFxj`v@bAKBCL?LGn@KROPEJKd@EP?FBVM^Dl@IH@TGZCZER?RIREj@GR?LERAXEb@?d@IX?`@?H@rAC^@j@ERCN?h@GZ?h@QNANIH@JIb@ILIbBi@H?`@IhBMz@OXKx@O^ON?^ITATIj@KpAKPIFKT@BCb@@JABA@GGYIo@?a@ESBCGSA_AKm@EuBM{@E_BGIUMi@HIFUDeA`@mAXw@\\e@JaBJW?WDKAm@H]@EAGBIAq@H}@@QBIAo@DCBOCS@{@HOEMJq@DcCp@oATw@HK?IBm@DaAL}@Do@Ns@Fu@Dq@JcBJg@@e@AM@u@Ca@D_@CyAAeA_@YESKOCi@Sk@MOIKAi@SUAM@MBcCbByAx@a@ZWHQLa@^KJCHiAdAgAnAE@s@r@_@XUVELDh@Lh@Fb@DR?HZ~BVvAFRFf@VLFFD@RE^@DCh@GHEPARIT@PKRANGPAf@OBGAKE[E{ACOAYEQE{@EY@KAMSuBGkA@YISA[Io@Eq@IOBIXGd@a@TMTQdAm@x@m@d@Sn@KL@TJRBNHz@VdCz@r@Lt@?^@`@Cv@?j@?PCJ@JA\\@lACz@KJEj@Gt@OZAx@Kd@AXEb@CxCc@^C`Be@nAUjACPEr@CP@XErAGDCJDr@KtAEVEJ@b@GB@TCr@E\\GRKpBk@b@UNA^Od@IHEFDNCFCEEGDUIOBYNUBa@POBWLEAED_@Du@ZSBc@LSDcBFo@HYAKBeBHo@F]CcBLMCKBGCKBs@DQD_@FoA^O@m@Rs@NQAIBg@@c@Ju@BIDeAHGFOAcANOAo@JaAHID_ABIB]BUEKBSCKBMC_@BGCc@DSCI@_@?W@a@A]KKAc@QUEUKMCQAc@OWQM?SKi@QUEM?}Az@{AbAiAn@GHE@SNYLe@`@a@h@KD]^EJQP[b@o@n@"
  },
  {
    id: "72b48cb3-7e99-4bd1-9422-9268c3bd0bcc",
    date: "2026-08-10T05:15:00.000Z",
    title: "6.5km Easy Run",
    sportType: "run",
    distance: 6509.5,
    duration: 2288,
    speed: 2.845,
    heartRate: 160.8,
    elevationGain: 40.1,
    completed: true,
    source: "strava",
    externalId: "19677084166",
    map: "inijFxk`v@r@Ox@I^GXC`@KVAtA[LKN?^GR@^CvB_@tAOFCX?RIH@j@KN?LEH@HAz@An@?HCHBr@CZ@R?LEh@ALCN?`AInA[RIVGNAPIFAj@UB@BB?n@Bb@DJA\\@X?d@Dv@C\\HhA?v@HHJCRBpA_@d@[x@_@d@_@f@SHKv@a@XUx@e@ZURGl@e@LCNM`@O^YNEFa@ZgA?GGIAQK_@AKIQASDIIMAKI_A?SGi@@MCi@IYCYAiAIe@@QIWASBUGaAEKMGKA[FULK?MFI?{Aj@g@Jc@LGFs@RWBKAMBKAEBwAHOA_@Dk@@SDYAKDKA]Fm@?g@HgB@m@DODWDIDWBIDUDGFo@HwA\\[@IBs@DMFy@DE@c@DIBc@@MFU@g@H_@@QFa@DOCeAP_FFcAC?DDDF@PACGGAG@IAo@?G@{@Si@QOCa@SKAa@O[GOKgAYIFEP?b@CKBWFIFCLBPJH@FDVFFD~@Vt@Zz@TBBZDFBN@HCp@D~@At@@hDEj@EfAQN@LEb@GHEL?PG^Ax@IN@r@MH@hASf@EFC^C|Bk@`AS~BOd@@LCfAE\\EX@r@Ct@Kn@A`@GR@PEz@Eh@M@Cr@SPCl@UXOTEPId@ATO?CECICIFYJU@g@LIF_ARGDI@[PaAVS?MDY@i@AqDZyBFs@HQC{AHe@D[JQ@aAXQBMFa@JQ@WHOAmBTM?YFcAHoANK?ID]?e@Je@?u@L{@HMCa@@MBg@G]@KAQDoA?IAs@@g@Qq@KYOE?IDIAUKGKMGMKOEIEg@KCCOEi@Ta@AaB`AMLkAl@c@^{@f@}@~@IFiArAKFs@x@MF]^"
  },
  {
    id: "1c02d213-105b-47cc-821a-2927285ac739",
    date: "2026-08-07T05:13:22.000Z",
    title: "On Off Ks",
    sportType: "run",
    distance: 6636.4,
    duration: 2192,
    speed: 3.028,
    heartRate: 173.8,
    elevationGain: 42.3,
    completed: true,
    source: "strava",
    externalId: "19636426976",
    map: "emijFpk`v@`AOjASHEb@ENGH?p@MVAjASN?TIpAOdASXEH@z@ML@tASL@JE|@AT?JBj@?^E\\Bz@GLELBPE`@?FEHAbAWBClBe@j@YlDa@bAObBc@`AOTAVIzBYz@OP?JC@C?KK]E{AKiAMuBKmAAeAEu@?UEMCCI?e@JiCz@_@Fa@Lw@Xw@Nm@DgAB[FY@OFKCg@DWAs@FD?q@@[DyAFc@?q@DgDt@[Ly@Lg@BwBVgAHmANg@Du@NwAHMBKAYBm@Au@DOA[@WCKBgACu@@w@WMA[OmDiAMCW?y@Vm@`@MDWTo@XWTYL{@n@GHIRLbCDX?^Jx@Bl@HZDh@Bd@JbAHfBFZFz@PJ^@r@Kh@CTGbC[TG`@EXGlBWd@M|@IXGfAOZIVANETCh@Qb@CJGREHE^EJEP?LGZAHCdBO|@Sn@Cj@K\\?v@OX@TCN@`@Cf@BnA?ZEjAEl@GP?VIZCh@UHCNI\\Ed@Uh@MPID@pAOLCT?j@GdB_@f@QPCHE^E\\It@GJEp@GPIrAK\\IBKGk@EO?QIw@@OMgCEW@GEKIi@B]Gm@?QKw@@IGGWKQBo@VG?}@VSLcATg@Ry@PaAHKAWD]?KD_@?UFW?]D]AmAJe@A[DI?GB{@Ak@DkAPaCn@WBYFkBP]FI?KFY?SDa@BMDIAWFs@Fi@Jm@@w@HGBgBHmD@"
  },
  {
    id: "062dcc50-0511-4e6e-a1c8-7d0719c384ed",
    date: "2026-08-05T05:17:40.000Z",
    title: "12km Hotspot Long Run",
    sportType: "run",
    distance: 12011.9,
    duration: 4250,
    speed: 2.826,
    heartRate: 164.5,
    elevationGain: 66.9,
    completed: true,
    source: "strava",
    externalId: "19607959002",
    map: "imijFlk`v@~Ca@pBa@vAMXID@DHC\\DT@bABPFfA@nAFR@v@HfA?XFR?ZFh@FLF@d@QZHz@]RC`@QVEp@WbAUNIlBe@lBk@`@Gf@S`AY^Gh@Op@Ul@Or@IZMr@QtBgAd@[n@Wd@]NGhAy@XKd@_@LCdAu@JAb@[^QDWP_@Hc@@O_@kB?KKm@A_@KeACcAKg@@[EW@SSgBB]I_AEEKAWDOGiAZ_A^w@NkAf@w@HsBFe@LEJ?|BAL@jAD^?p@D\\?b@BPAPBzA?ZAFGBmALeAd@U?qAh@m@N{ADoALc@@w@Ek@Dm@?qBL[HoAL{Dl@eDb@[J_CXs@PqDd@cB\\gAHaAVY?EDiAPaADe@Re@By@TQ?]Hc@BIB[Bq@LKQIk@Qu@y@_GK[Em@@IDId@Wb@e@^WpCsCV]n@i@vBiA`@e@^IrAaAVAZG?GEM@ETIFEv@]d@_@`Aa@`@Id@Sd@Gp@SzAYv@Ir@O`A]^SPGZUx@a@hDs@n@QH?l@Ul@EvDw@bA]fAUb@Ol@MrC}@VCVKn@IrBI`D]tAEz@On@ApAI@D?n@DPCLD^@XFTDhBJ|ABLFvBg@PK?m@Vq@N{@Zq@N_@NoBZgCJoALoCLKA_CHeANoCr@qARcEZw@PQ?iAPiCVaCBaACwCBIAa@Sc@I_A_@m@M]Q{@YK@sAZaBfAWZe@NeAl@c@PCFNT@PDP?`@DVBj@F\\J`BDPD~@DNFp@Bp@TxBDP@t@EJa@DSH_@BYHu@F{AX]BMGEIIk@Ce@g@kCASQeAUkAEa@FYNEn@a@b@e@l@g@JO~@y@JQRSl@s@jBcA|@o@j@Wx@s@\\OPARIhDdAx@\\nAXvABj@Gv@BzDGvBUrB[fCS`AQfAILGZEx@Up@Kv@UpHYj@IzAEf@ItAE~@QnCaAbAYj@MP@DC?EKKKHU@c@Rk@Hs@Xy@Pc@TmATsBFw@La@?[F_BHk@Cm@H}@?y@DkB\\a@NsBb@oAH{BZMA[HyBPu@LsCPuB@g@Bk@E}A@y@Ou@U_@Gg@a@oAa@[I[AyAx@e@^a@RgDvBWV_@d@QLo@x@kAhA]b@MDCFo@h@ENBLF`@HZLjAFVB`@H\\"
  },
  {
    id: "2cdbe56f-88bf-4c84-b6fb-7ed4255f97b2",
    date: "2026-08-03T05:19:30.000Z",
    title: "8km Easy Run",
    sportType: "run",
    distance: 8021.5,
    duration: 3122,
    speed: 2.569,
    heartRate: 157.2,
    elevationGain: 43.6,
    completed: true,
    source: "strava",
    externalId: "19578476987",
    map: "wmijFtk`v@n@MJ@PCp@QbAKx@Sv@MfAIt@SR?PGb@Ct@O|@ILE^?^GNGJ?JC`@CJ@bAETB^CL@dAAd@C^ERB`@IZAJGz@OFE^MTCVOJADE\\IFEHDZSP@PCVIVALE`AE`@GF@BHE|ABXE`@BR?`@BNFJ@P?nADBX@HCTQr@a@RIVSZOt@k@\\SLCZYHAVSHOTMh@MDGBQLa@J_@@OKa@Mu@?OKm@Ec@IuAEWAm@G[SmCEo@@ICM@SCg@CE_@QWBu@XG?e@N_@PYHe@Fq@\\{@NoCJWFqAD[DS?GBIAe@BU?s@HSA{@Fo@@iAPc@Pc@F_B^eCTGBu@FGBS?WFI?u@JMDk@@IDIAIBm@D[HU?KBO?MBqA@CD_@EOBq@E]Da@Cm@@o@A]O]GKGuA_@}@]G?GGe@OWCS?WJa@ZUJSPm@^I@iAx@s@ZEHYFU`@UNeAbAQV_@XCHIDINOL_@d@gAr@GP@XLn@?VN~@Nh@J`ALf@BXDLCDBNNt@HPZP|@MN?JEb@IR?JENAZIF?p@ML?FENCPCL@f@OF?DC`AK\\If@EJEH?x@QF?RCH?nAQb@K\\GL@NIpAQ@NATDbABPAh@NjAH\\DdA?TDh@DVBh@DT?ZFp@Fh@DLNHFCPAp@QH?VKPEFGn@Qp@[b@GpCy@N?XKLCj@SLCpBm@LAVOrBe@t@UJGp@KJGb@Oh@ML?h@Ul@Mb@QRAFE\\IFGL?FEb@EVKLA^OD?XILAPQZMh@]RIj@_@^OTSn@YNKBGHCXYJAHILETQ^ORSVKNM^KJGLOTIDG?UH_@Rg@?KEMI]AQI[AICICm@Ka@CiAKkAIk@MmB@EG_@?OBk@EUC_@_@Ki@F_@PWBOHSDa@No@N_A\\o@NY?UDk@BWBS?e@Do@DMBO?E@Y?QBIAGBQ@QCIBQAs@HUAUBO?MB]AqAReBf@W@_ATcBLGDa@BkANKAKDW?gAPM?q@JO?kAN_BBg@DIAa@@MAy@@IAe@H]Ci@AoA[}@O?ACGGEKCIIM?YIu@]QGO?k@Nc@NQNE?ONKBUPQH]XYNu@f@[ZE?CLAl@HPFFAAEf@Dp@FRD~@"
  },
  {
    id: "0b634f49-537f-4f7f-a8c8-19f56b5284dc",
    date: "2026-07-31T05:18:48.000Z",
    title: "1km Repeats",
    sportType: "run",
    distance: 5983.7,
    duration: 2093,
    speed: 2.859,
    heartRate: 169.6,
    elevationGain: 41.5,
    completed: true,
    source: "strava",
    externalId: "19538375156",
    map: "imijFrk`v@XIlAMHGn@G^KPAx@OdC[TI`AK|@Q~@G`@IL?RGT?p@K^?x@Eh@BRAfA@v@IZCJ@DAn@C^OfAWbAa@nA]P?BCD@PCHC\\CLC`@Ab@KbBYb@O|@SVA\\KbBU`AKJCj@EFK?IIi@MoBKi@GsCSwA?]EaAGIWKc@HyAh@mBh@YLeATuBJ[@YFOAi@Dq@FaBDw@DKAa@@g@BEBk@By@Ns@Vc@F]JqAToAHc@HcBLmAR}@DGBaALy@Fs@?wADe@Ak@B_AC]@k@A_Cu@_@IOGYEeAc@SCODGPAHF|ATzCAPFbAHp@Bt@F\\Ht@?ND\\EKDRD`AFb@ALHV?XDn@FLD@TCv@Mb@Ab@Kp@Gd@KhAOnASf@Mj@Gf@Kj@GNGL?^IL?JCTA|@Ql@GfB[nAI\\Gv@IL@bAE|@?l@AP@D@`@G\\ANCH@x@GJEfAUZQ\\CPK`A_@hBUP?h@IH?tB_@BERCXMPALGbCYpA]T?LCZ@LCFIQkA?s@G]CeAEIEa@@MEk@@ESmBB]GcAACKCQ?QIeBh@KFM@UJ{@Va@PUBm@NsBJm@H}@BUD{BFaAHM?ECKDKCyALy@L[J_APo@T}@L{@Da@H_@BKBI?_@FI?UDM?a@H_@B"
  },
  {
    id: "2189b538-9b68-4901-85b9-f1997d4f9aac",
    date: "2026-07-22T05:10:19.000Z",
    title: "8km Progressive Long Run",
    sportType: "run",
    distance: 8026.5,
    duration: 2762,
    speed: 2.916,
    heartRate: 176.8,
    elevationGain: 49.5,
    completed: true,
    source: "strava",
    externalId: "19413106892",
    map: "wnijFzk`v@j@Gb@K`@E^KZ?f@M`BWBAAQBGX@\\Gz@@DAJKTETAHFB?JCTA`@IXA^IXALEf@GXGh@GN@fAIt@Bt@Cn@@LCTCN@JCV@XGTAdASNGz@U^Od@QPCNGXEL?PEL?p@Md@Ap@KF?HJCx@?pACVBl@Cf@BlAGJAJEFu@ZMLGCCO@OK}A?_@GaA?}@E{@?SDWFEPAf@?f@IRKTE|@UZEb@KTAxAYXARE~@KLGd@CJE?GEMIaAI}ASaB?UGm@@MMmA@i@Ci@IYICWDQEM@eBl@s@Py@VWLi@JuALQA_@DiAB_AJKAk@Dw@@cAHkA?m@Do@LoA\\OBeAX]Fw@Dk@JaCRc@JQ@YD]BsBPGBa@@SDy@BSA[B_A?UBs@GQBkACI@i@OIGe@ISKy@UcCy@IAK?y@d@{@n@}BrA{@l@KBIF_@^SXURQVy@r@INKLwAnAUZOFGVBf@Lv@FRR~AJf@Fd@H\\D\\Lj@B^FJHBdAGRGfAKJEbC_@vAOf@MTCXIr@Il@MdAMZIdAIf@KZAXKZCz@SfBS\\IVAPEn@IrA[r@E\\I|ASn@MT?p@KNET?p@Kn@EJ@JCh@?RCfCAl@GVAT@JE`@Af@MZGTIJA|CeAfAKJ@ZGP?~@ML?BD?NCLCp@BZElABt@ArAGNAPOFYP]PG?CACi@@YEaA@SGm@AoAGo@@m@DKFEzBS|Ag@b@EdAS^C^I`CWTEHI@IKm@QyBEuAOqBMs@?q@Ki@@SGI_@BSCODYJ_@HkAb@SBaA`@w@Lk@?IFa@FSCk@B_@F[?g@F_@?q@FS?QAW@OBM?c@Di@CgAJ{@PeAZcB^qAJOD_@?eAPKAMDa@@qATY?mCZi@@M@i@?WD_AEcA@KBa@Cy@Ba@MKAWMyAc@IG]ImAc@i@KQD{AbA"
  },
  {
    id: "3e56f827-254a-4c5e-b636-1cc8600fc538",
    date: "2026-07-21T05:10:41.000Z",
    title: "6km Easy Run",
    sportType: "run",
    distance: 6168.8,
    duration: 2532,
    speed: 2.462,
    heartRate: 159.4,
    elevationGain: 40.4,
    completed: true,
    source: "strava",
    externalId: "19401339663",
    map: "{nijFzk`v@NEd@CHEz@KfASj@EXKJUBApAMDET@LEH@REH@DDB@JEPE`@Ap@KTAv@QhAK~@MJ@TC~@Cz@@h@Ip@BTEV@PEZBFCd@CNGH@x@YLAJGH?ZILIp@WH?\\OZCD?d@IXAvBUtBo@jBS\\CXMH?v@Oh@GP@JALIDGGWEc@Cs@Gm@AiAK[Gq@?g@EM?QCG?UGi@BSGSCm@KCWFOGQ@_@NYFs@Xg@LO@y@^qATY?uAHIAy@Na@AqAHYAeAJi@Bi@A_AFiANYLeAVIDi@FIDi@FS?IDw@DaBT[@o@LY@_@Fe@BoCZw@?e@DkACs@DQEWBWAu@?_@OIAUKe@OMGa@GaA_@c@Kg@OI?E@GRE?GE?GFKD?bAb@bBf@f@Tl@LHFXDNFb@BPC^@TBn@Af@DXEr@?f@CXBZGRBXChDi@VAl@Ij@Cj@I\\Ct@MfAG\\MTEFEx@Mz@SH?ZEBE\\CrACNE^?DCn@En@?ZEN@p@IbBGn@K|@ANEVALEp@ULIv@U^QdAW\\MNAZMBBa@HWEa@LABe@Jk@TeATw@ZaARyAH]Ae@Ho@@SB_@?WDSAc@D_@Ci@Jc@CMDIAIDs@?EBQ@kAPWLm@L_@L}@NWBKA[F}@FeAPm@BOFcANmADg@Hs@Be@Fw@BI@I?QBk@CcABqACe@@a@MYM_@IYOs@MiBo@k@KI@SHi@b@mDvBUT[XKDCHB`AHj@@bADf@FF@h@"
  },
  {
    id: "e650bc7b-f865-4a2b-87ff-9b8d14860046",
    date: "2026-07-20T05:12:56.000Z",
    title: "Morning Run",
    sportType: "run",
    distance: 5034.9,
    duration: 2099,
    speed: 2.399,
    heartRate: 156.4,
    elevationGain: 32.4,
    completed: true,
    source: "strava",
    externalId: "19384455301",
    map: "ctijFfz`v@H`@B`@Pz@NzAJf@HFPATS^ORClBo@LAX?f@Ir@[RU@IGm@Ai@Iu@IeCY{BAg@M}AAk@?WFIf@KHGD_AEq@@gASeBIoBIi@OsB@OFMJA^FhAAxAIFHRnDDtARbCE\\?VIj@Hf@Gh@@z@PhCRpELhBBTLNr@GZGt@WrHsBv@WxBi@dBi@dCo@f@GLGFK@KYgKD[FI`AMxAKd@IL?FBBJEbAAhA@^Nf@An@Bv@BLFBTAJEx@i@VKt@k@TKnBoAZQbA_@DGHg@Rk@Hc@]yAKw@SmDIi@A[MaBE}AG}@CEGC[AM@o@PmAb@uDbAmAHmADwALuBFyAJo@Ai@H]@oATk@PwBd@_CR_ALi@BcBTeBNk@HmBDe@De@AeC@y@C{C}@kBo@YG_AVg@Tk@^"
  },
  {
    id: "323e723d-03ef-41f9-925d-ef280e4d58bb",
    date: "2026-07-18T10:42:30.000Z",
    title: "Walk",
    sportType: "run",
    distance: 2377.1,
    duration: 3110,
    speed: 1.02,
    heartRate: 89.2,
    elevationGain: 2.6,
    completed: true,
    source: "strava",
    externalId: "19361835964",
    map: "yddkFn|ew@ATCFIFm@PiC^EDGJERFtAJpAFnDFl@DHHLPJBFH`CNRJZFFpARn@T|@x@l@nAKZ@BQROfAAt@B^FX@f@D`@Ej@GPAJWHULWj@?BDBx@mANMDU@[AUQeAE}@Do@P{@Vk@TKLAPEHI?IOw@I}@IU?UMwAGQG_AKcAEKWOIA}@RK?WHo@LM?ODIHYBIFQEKMG{@CaBESE@BE?a@EgAGY?wACaAIe@Ey@C{@BYK_ACy@W}COoA?QEKASAE?JAIE[BBAKKy@"
  },
  {
    id: "86b980f8-1616-4768-baef-a377cbd69482",
    date: "2026-07-16T05:07:52.000Z",
    title: "Morning Run",
    sportType: "run",
    distance: 5007.1,
    duration: 2213,
    speed: 2.267,
    heartRate: 152,
    elevationGain: 39,
    completed: true,
    externalId: "19332196610",
    map: "ctijFfz`v@j@bDJhAJ\\DBJAjBk@RIFK?Q]mDCs@s@eJAk@BEFEt@IJBBFVjDP`BDt@VtCJhBJVHDF@RGVMf@KDCBM]_GUiCQcC@a@Cg@BKFGbAGh@KJ?BBHfCTbDJbCJ|@H\\@n@DHHBxA[RO\\A^Mf@IfA[zAi@l@Ml@Ub@Iv@Wh@Iz@S|Bo@b@Ql@Od@G`AY~A[`A]T_@t@_@LKPSDMBiAA}AAc@Bo@?}@B]HKnCg@zAUXADHD|@H~@Nh@DZDBP?XE\\OVYFc@Tw@@MKg@[yBUiDGa@Ai@KyAIk@?w@Ei@CEICy@Ds@P_Bj@m@Nk@Rq@LyF\\_@Co@FWFyCJmAJmATsA^iAR{BRmJbAyABgADgE?g@OyFkB[EMBKDcCbB"
  },
  {
    id: "4d77f34c-f793-433c-a0e3-6b48a048dc34",
    date: "2026-07-15T05:15:17.000Z",
    title: "Morning Run",
    sportType: "run",
    distance: 5271.7,
    duration: 2255,
    speed: 2.349,
    heartRate: 149.1,
    elevationGain: 28.8,
    completed: true,
    externalId: "19318739697",
    map: "ctijFhz`v@Dd@p@|DBZFHL?nBi@nAc@xCw@\\ONOx@WZURAt@MRCTGXAf@Mr@SrAg@bAWXK^Iz@[jG}Aj@ORKnBe@HE@GGc@CcB@e@DG~@?JDDrBBJHHLDN?bA[R[d@S\\WFKLa@Hi@?_BEq@D_@?gBBMFGp@Mv@Sh@GN?BJZ`EDVPLJAn@a@\\Cb@Up@SJQF]T{@@Si@iDOgCIu@A]MsBKcAEcAKIq@@{Bt@aDx@qAN_BFYFAFFVB\\DrEB^FrDAr@EHo@Du@Lq@XmA^_@Ns@Ni@@GCCG?g@CcAc@_KOwAGIaAXEJTlFFnBD`@FzACf@Bl@EJEBgA?KCCG@s@Co@WyDCcBSuCEMGCeAHk@Hg@Bg@J_AFsARY@_@D{@B]HyAJu@B}AAaC@YCqFeBoAOWHgAv@}CjBYTEFIZ?`@\\bE"
  },
  {
    id: "edeb8adf-89c6-44b0-8569-a23c0764d529",
    date: "2026-07-13T05:10:14.000Z",
    title: "Nike Run Club: Monday Morning Run",
    sportType: "run",
    distance: 3841.6,
    duration: 1505,
    speed: 2.578,
    heartRate: 159.4,
    elevationGain: 28,
    completed: true,
    source: "strava",
    externalId: "19290134415",
    map: "itijFly`v@Bf@Lv@VfAVzBNHb@Sz@SRIzAe@TAh@MTAf@SRI^e@lBk@z@QR@PGTAxC{@t@[hA]f@Kx@WrBg@PIvBk@PQlAYT@v@UrB_@t@Wx@a@LSRIb@[TKT?|A{@r@e@\\[d@UfAq@lAi@d@QL}@V{@CY[iAAWGUKiAEs@@[Ms@MyCIs@?UEWCo@e@?SGoAd@}Ab@SJ_B`@kBLeCJWDqBFy@Ji@?sAFqARmDx@g@FaBLSDkAJqBVqAJoANi@Bi@@QBsAEy@BgBAy@YcBe@iA_@}@OSFETF|BLbB?ZLpA"
  },
  {
    id: "390eb18f-e577-467b-90af-d9dad2a39c93",
    date: "2026-07-10T18:09:03.000Z",
    title: "Evening Run",
    sportType: "run",
    distance: 3769.6,
    duration: 1369,
    speed: 2.77,
    heartRate: 178.8,
    elevationGain: 25.4,
    completed: true,
    source: "strava",
    externalId: "19259335647",
    map: "gtijF|y`v@R|@f@dEJRFDHAx@]tC{@tBi@tBw@jA]vCs@f@MTKjBg@v@YxA_@zAc@~Bm@tC{@hCg@x@U^CTMPQRMjAk@~BqAx@k@r@a@lBqAtBs@DG@KByAk@{CEk@EkAU_CYiFGMGAgATm@DcDdA}@PsDRyDVe@?iAFiA@oAV_Cl@y@N}Fh@UFw@HgAJiADy@JoADwB@yBEgEoAm@Sm@KI?KLA^HtBLtAH~A"
  },
  {
    id: "ad886c23-4668-4a3d-a26d-2b1c31e207ca",
    date: "2026-06-30T15:55:03.000Z",
    title: "Afternoon Run",
    sportType: "run",
    distance: 2521.3,
    duration: 925,
    speed: 2.741,
    heartRate: 170.6,
    elevationGain: 14.6,
    completed: true,
    source: "strava",
    externalId: "19128724391",
    map: "etgtHcxlRe@rBSf@LWFU?FCN[fAYp@[nAUx@GHIBQKO?IFGNk@jCY~@uAhGw@dCQv@[hASfAm@zBYpA}@rCoA|FOb@gA|DOt@g@fBo@vC_@nAUfAIp@a@fA_@hBk@dBYrAY|@YvA{@pCQjAB\\FLHDTAFBn@f@LPTTPb@JHj@n@V`@b@bA^n@XXZDZb@xAzAz@dAj@`A|BnCf@b@nAr@ZZl@t@"
  },
  {
    id: "3b554871-8594-4d35-bb42-a84a2e849bc2",
    date: "2026-06-11T12:03:03.000Z",
    title: "Nike Run Club: Thursday Afternoon Run",
    sportType: "run",
    distance: 15576.9,
    duration: 5384,
    speed: 2.906,
    heartRate: 181.5,
    elevationGain: 106,
    completed: true,
    source: "strava",
    externalId: "18878119589",
    map: "imgtHqpmRDZj@~@GZD\\c@BQP_@nAm@pB}BzI_AlEMTA\\cBdGMVy@Xa@tBk@xB[n@wB`JObAm@hByB|IC^q@pCo@nBOXe@vBw@hCI~@iAtDy@nDYj@O`BOVYrAYn@}@hEYp@Ez@[j@k@nBoAdFIv@RLh@vAfAvAd@Pn@~@dBbBj@`ApF`GbFnEjKdPb@`AnB|B|AfCKVg@VqAY_@o@a@a@aBg@Qy@m@}@C]_DSwBaAcAkA{EqIiBuAoEgCiBqBYs@qAqBiBsAk@iA]yB_@uAo@cAc@a@{CgAy@m@a@sAU{DDaAXq@REv@h@h@nAHdB^vAl@~@|@^n@r@d@jBv@|Aj@NbB}@~@Rl@~@Bd@I|An@|DX|@rBx@fBlBj@hArAd@`@^NRZzAxArAZ~A`CfAVn@HvB`@j@bB\\nACLWM_A{@iCm@kA{A{@QSg@kA}@a@aAyB{@Ke@iAaAWg@]Su@yAqAe@kAYqAh@Pr@dApBzA~AtBvAnAZn@RBb@b@Vn@f@f@lB~CJZ~@lAb@jAfBfBr@|AxBbDpA|ApB~@tA~AvArCPAj@yBl@wFPw@r@eBb@YzDuFrCuCnCoEd@c@A]eAwBo@y@g@kAm@gAc@k@c@gAAa@xDiKl@y@j@sAb@oB~AkD`@uAvBiFx@eE`@i@n@{Ah@qCNIh@VfBAlAWPPlBWv@e@dB@F}CH_@PEPq@L}Aa@{CiA}@]k@yEkLk@kAaCeBgAgAe@UmBaBcC_BaCiAeCeBcBm@i@AaAXsAzAvBdI\\h@rB~@TCP{@rAuAd@It@d@NT|@rE|AbCx@tBhA`GKz@a@ZkCRc@]k@gAy@u@iCcAONs@fCYxAc@pASR_AnEzCdBp@lC?x@o@x@eChBqF~CmBzAGX@\\b@@\\s@`@SXj@TIHx@LRd@BLP?|AFXPLJV@`@Mx@e@b@WOYs@a@KY}A_AYI]u@w@DYb@Mi@kAeDsDqFkE}A_Cc@{B?]bAaDZm@jA`AnAlBz@`@^q@^qAp@sEl@eAfBeBM}@{@yAs@oC}ByGO{@sAqAy@a@wCsBkDaDwAgBE[dBwFdAeEp@iDNSfBsHl@mBVwAXu@^yBf@_Af@QF}@o@aBH}@"
  },
  {
    id: "c512d3ba-be18-430d-9fc1-5ed0ca5585ad",
    date: "2026-06-09T11:04:29.000Z",
    title: "Nike Run Club: Tuesday Afternoon Run",
    sportType: "run",
    distance: 2815,
    duration: 915,
    speed: 3.107,
    heartRate: 171.3,
    elevationGain: 18,
    completed: true,
    source: "strava",
    externalId: "18848959324",
    map: "utgtHmzhRJ]\\m@JUNSjBkAZe@RQ^i@j@oAnAkBp@sCRq@P{@d@yAMcBMSK[[e@c@]a@e@y@o@s@w@UMc@_@SUa@i@g@c@a@e@e@c@KW]uBSQSLQOaAgASOg@SQY_@a@g@]QQ]g@sAqAw@k@OQQQSWSMUS_@e@Yw@G]N_A?_@Ia@Ec@Bc@PeAZq@f@mBNs@h@mBXsATu@D_@J[t@yCZy@D_@Vy@l@oCJUF_@Xw@R@RENSN[HW@[fAiELw@NUD[Vo@FYTo@\\yBLYPs@JWl@mCTo@ToAVu@LUPSLPHWAc@Fy@KYQU"
  },
  {
    id: "d56163eb-be82-4320-9cd9-bd6b4fe4feeb",
    date: "2026-06-08T11:36:12.000Z",
    title: "Nike Run Club: Monday Afternoon Run",
    sportType: "run",
    distance: 7580,
    duration: 2649,
    speed: 2.866,
    heartRate: 181.7,
    elevationGain: 39,
    completed: true,
    source: "strava",
    externalId: "18835882884",
    map: "gpgtHovgRR|@j@lB\\xAFz@C\\@`@B\\F\\LVr@z@^r@pDpIRJLRVt@^j@LXTv@PPLRf@nA\\l@Xr@j@fAjAjC\\n@PPFZLVVv@`@h@pAtCHXNRXn@PRTp@Zr@Xt@Zl@JVn@|@RBRAnAg@NOx@g@LY`@_@Zm@RCR@LNNVJ\\LTRQTGPKfAcA\\a@d@_@b@k@x@g@PPHVh@MlC{@f@IRAXv@NVPJPGPQPKd@a@v@i@L}@Ty@D_@f@mBR}Ab@qBRuATw@d@uCR@NLPHbBbBv@f@r@j@TEf@_@d@Qv@i@LSJ[LUF[E{@PwAFYH_APy@r@kBLQx@gBh@gAZs@Ps@LYF]@a@FYJ{@t@qCPw@n@cBd@yBJYB_@b@qAZo@b@e@`@]RIf@]VITOVGR@TGd@[NOTKl@gAb@iAn@cAH_@x@cBOSg@cAIWYyAC_@Q_AC]s@uEGiBA_AC[EaCD{@C[Sw@OOAa@@aAPORyAPaBA_@Ec@A]E]?c@G_AYaEK]M[QQKU]e@e@Ys@y@kAiBSOq@eASMUGSMWAQFe@Dy@R{@JQ?UMg@Hi@Be@GUHQEmALaA@g@EQBSAU@]^Kb@Cb@B|@Sx@UNUEi@@SPKTSJUJU@i@TSRi@PQNg@J_@`@U@MPa@\\OTKTKWC]OKg@KS@y@OS@QMQSi@Cw@MC[B}AFy@PSLWH[RwA?]C[K_@Ow@M[SQQIa@_@[k@q@yASu@g@kAc@qAOU_@c@K[C[i@aAMQSMUIe@_@a@a@SEOUwAkAw@i@C_@L[T@PO`@mA@[Ec@I][k@KWaAkDQQUu@E]OUK[m@y@_@_@SOQG_@m@NW?_@H_@IW_@g@a@YSWgAs@OUa@a@g@WeAgASOQEa@e@SIKSUISOk@y@q@s@i@WOUUQOS_@[SGQOOGSQOU"
  },
  {
    id: "6f0cf5b2-4619-48bd-8600-6ec7191d8f97",
    date: "2026-06-04T17:00:39.000Z",
    title: "Nike Run Club: Thursday Evening Run",
    sportType: "run",
    distance: 12518,
    duration: 4504,
    speed: 2.782,
    heartRate: 182.7,
    elevationGain: 102,
    completed: true,
    source: "strava",
    externalId: "18793747975",
    map: "emgtHcpmRh@fA?z@KTQ?a@`@Wt@M|@aBdGWn@_@vByAxFYv@Mv@g@tBmAbEa@nBi@jBSDUv@QGMRm@rBC^Wp@aBbHYz@Qx@Wn@K`AYp@Mv@a@nAK~@w@~BWrAk@jBWnA[n@B`@g@rAKt@[jAWl@Ox@C^[v@sAzFc@lA[l@S~AiAxE[r@k@tCUr@KUm@cAg@gAk@aAk@{@aBmBmAs@sAYi@?SL]j@E`AXbERz@^n@d@\\nC|@r@v@n@lALx@t@jCB\\z@~AV@d@ZC\\VFLOx@zApBdCv@p@xAt@hCxAp@r@|@tA\\b@J\\nBpD~@jAv@f@jCp@bBH@`@b@^`@jAXB`@\\RApAxAPKt@p@PCFe@E]Wy@SM[o@sA}A[u@SOkAgBiBqCg@eA_AkAg@_AoCoD{AeAe@g@g@U{AuAYk@{AqBQNN`An@xAhBrBZr@bBx@F`@NTz@TRRRr@Zl@|@Xd@hA`@l@RDlAr@Vl@ZrAXn@Dz@MXsDm@[o@?a@F]M_AMWQQoAUSOg@aA[oAiAmA]mAaAcAg@Gc@]mAsBc@c@e@[_Be@Wq@]yCq@aAJYHaAA]Ys@e@_@SA}Az@QBiAe@o@wCOY_@i@iAq@q@w@Ss@WwC[w@_@g@i@A_@d@M~@JbDHz@`@pALTx@j@xBp@p@r@`@l@f@fAVvA`@f@\\p@`AdAD\\`@`@h@fAb@d@Xj@t@p@l@bAb@`@~BrAt@dBrAzApB~@fAnBnAhBp@r@~Ar@|@NpCLlC`@`CtCd@jAd@f@pAj@PCp@r@p@z@rArCRHNOR}@\\yCZwAHaAf@mBnAcBzAcBr@eAfFuGl@aAn@u@Zo@o@kB_@c@[u@_AuAqByDDa@fBcEdAkCHa@Zi@`@uAdBoE`AuBdA}CfA{B|@wEt@_BZm@^wBNWPCz@PdB]`A?nAQpC@d@KL[J}CNKT}@N{@@a@O{AQy@MQe@U_@e@s@{A_E}Jm@_Au@_@wFeFgAm@cA}@cF_CwC_B{@Me@HJWKYmBuAg@MyDiB}A_@sBqAwB}@u@m@eBe@qBqA?a@p@eBf@kCfA}D"
  },
  {
    id: "337ed07a-9f4c-4d01-888e-d77771a3ab59",
    date: "2026-04-07T10:24:59.000Z",
    title: "Nike Run Club: Tuesday Afternoon Run",
    sportType: "run",
    distance: 4014.6,
    duration: 1254,
    speed: 3.212,
    heartRate: 181.8,
    elevationGain: 33,
    completed: true,
    externalId: "18010890750",
    map: "otgtHo{hRPQ\\k@PONUf@_@REr@s@HYp@o@j@gANQNWPKPG`AfARNbAnANT`@ZPXd@h@PERHPNrAvB^p@PPZf@RHRCPMd@iARu@LSFWLUH]fBeE^mA~@{Bf@gAh@uAFYx@}AV{@LQH]L]R{@Z}Af@qBb@m@Zm@Zs@L_BRQVDf@FTEj@?RIVQTGRFh@K~@Ad@Ef@M~@BTBPJLYCc@DgA?[B[PUJ]LUDa@Ha@?c@K_A]yAOOi@WQS_@q@q@{AKa@MSy@}Bg@iAM_@q@eBuBuAc@a@aCmBq@u@QMUGQQi@[QQWIOQ}Ay@UEe@]e@USCWMWOeBy@UEk@BUAOUD_@JYRARILSXs@rB{Dx@{BNSZm@C]QWA]K_@s@o@QQSISUQKcAkASG_@_@QIy@s@s@y@u@g@MSg@e@SKe@g@OKUKOWg@[e@c@{@o@OSOMMSSMQEs@{@G["
  },
  {
    id: "1dcb17a0-0b4b-4459-9621-90fff25c8797",
    date: "2026-04-03T10:18:03.000Z",
    title: "Nike Run Club: Friday Afternoon Run",
    sportType: "run",
    distance: 2700.6,
    duration: 839,
    speed: 3.254,
    heartRate: 160.7,
    elevationGain: 14,
    completed: true,
    externalId: "17959975377",
    map: "ypgtHi_iRROLSNMdAgAPUXm@\\i@NMh@eAL[Fa@Pw@b@sAj@{BNW@[Q{@w@kBQQUIMUQIMUSOMSy@s@a@k@QQe@QQSkBgBQ]I[E]YqAQCQHOM_@e@QISSeAgAOUg@_@_@e@qAcAu@o@QYSKMU_@c@k@Ya@_@MSGWG}@@[j@sCD_@v@cC^yANOHeA^sAXuAD]`@kAfAiERaAbAmDlAgFV{@b@yBDa@NSRs@LWFc@`@uAD[t@gCF_@P[RwAXy@^{AFa@Ts@NMPANOCa@FYS}@"
  },
  {
    id: "557952ae-ab81-447b-979b-22e8fc9cc5fd",
    date: "2026-04-02T11:18:26.000Z",
    title: "Nike Run Club: Thursday Afternoon Run",
    sportType: "run",
    distance: 2787,
    duration: 854,
    speed: 3.287,
    heartRate: 169,
    elevationGain: 7,
    completed: true,
    externalId: "17948656849",
    map: "wtgtHyzhRn@qAPQd@e@r@c@^c@NWRINOlBaDZq@XoAp@sBFc@H[B]ZwAEy@Yo@SSMUg@]eAmAc@Y_@]OWSOMSc@[s@s@_@g@UCg@_@U{@Cc@K}@QSWHSQcAmAy@k@g@g@QKg@_@c@c@QWaCwBOSa@]QIQOOWSOKWK}AD]JYZqAXqAN}@JYDa@ZqALWRs@F[dAyDb@qBJWR}@Vu@`@qBVo@FYl@mB`@cCb@uAn@kCPBG[D_@N]D]NQz@{Dl@qBfAyEVu@Py@JUNWTAP[K_@Bc@W{@"
  },
  {
    id: "6b2d7dc1-ea39-4c2b-b0b1-92252bd45c2c",
    date: "2026-03-28T13:09:35.000Z",
    title: "🧦🔎",
    sportType: "run",
    distance: 4000.2,
    duration: 2170,
    speed: 1.884,
    heartRate: 155.2,
    elevationGain: 62.8,
    completed: true,
    externalId: "17889446958",
    map: "mtetHaiiRf@k@ACuBMuIgHeAgAYc@OMq@g@QGEAGBIN_@hAwArDKl@@QBAj@mBj@{A`@_ALa@?KCG_@QkAaAMOWS]e@k@[QMOUa@[g@g@SOIBWXSZgA|@_@Rw@n@UD}@f@uDhC_@\\QTILCR@BZHHAJMXm@XWDDLXHNF@TABn@FTF@LEH@Vd@BV?h@B`@Xh@Hn@Cc@COIMIEY@KEi@g@U]KGCDBDGOU]u@q@]USIQHKLSf@iBrGQ\\u@dBsApBk@j@a@p@m@h@q@\\OPYh@]jAMr@M~BAfAFRHHB?HMNKQLSEEQ?YTsDJq@Xw@f@{@p@e@~@y@TWLSTOVi@PUTc@JI"
  },
  {
    id: "0bb39497-4f74-4e68-84b2-29bb81805078",
    date: "2026-03-27T12:29:09.000Z",
    title: "Nike Run Club: Friday Afternoon Run",
    sportType: "run",
    distance: 2712.5,
    duration: 821,
    speed: 3.32,
    heartRate: 165.8,
    elevationGain: 11,
    completed: true,
    externalId: "17876364172",
    map: "cngtHibiRb@a@`@g@x@cB^k@z@sCj@wBVw@Ja@EYE}@KWEa@QWOOeAs@a@i@c@]eBiBe@[SUQIq@{@a@_@OUY}AI[O]QDSAOUQMo@s@u@i@cAcASIOMMUgAeAeAw@a@g@UIs@w@KWQMOUQ{AB[LUJ_@\\}AD[L[N}@JYZqA\\o@B_@nAaFTqAd@qARy@VyA^uAd@wALw@l@oBR}@JSfAgFXw@R}@`@sA^_BrAaFZsAD]L]D]HYZi@R?LUEa@Da@Ss@QQ@]"
  },
  {
    id: "b84d0abb-c186-4a6e-b289-633d6e369973",
    date: "2026-03-26T12:28:19.000Z",
    title: "Nike Run Club: Thursday Afternoon Run",
    sportType: "run",
    distance: 2551.6,
    duration: 745,
    speed: 3.467,
    heartRate: 183.8,
    elevationGain: 16,
    completed: true,
    externalId: "17864834929",
    map: "}ngtHkaiRRQ`@k@LW`@e@vAiCNi@EyADZPGT}@Zw@V{@J[@[F]I_Aq@s@KY_AqAQK{@s@MQOMa@k@w@q@a@e@SQOWQOUMc@g@KYSqAI[UESHOSe@]c@a@a@[c@i@_@YqDmDc@[c@c@SMOQc@]OUOKQSI_@?e@E[@_@Xs@R}@L_@PcAVq@ZwAL[N_AJW\\uAXw@`AuEr@_Cn@cCn@oCL[N{@Xs@D[dAgELy@PSJw@b@gAL}@Vw@R}@JW~BcK"
  },
  {
    id: "557a28ad-29c0-451c-8251-2ec8d0177a4e",
    date: "2026-03-20T11:12:44.000Z",
    title: "Nike Run Club: Friday Afternoon Run",
    sportType: "run",
    distance: 2781.6,
    duration: 884,
    speed: 3.168,
    heartRate: 174.7,
    elevationGain: 16,
    completed: true,
    externalId: "17789693523",
    map: "gtgtHq{hRd@gAb@U`@[r@o@Zg@NK`@i@f@aArAcCfAwDR{@HYZs@J_@F[I]OWUOSSQSg@i@aAqASO_@c@UOQSu@i@aCkC_@i@Ma@E_@M]G[QKUJSQiAsAg@]_@]y@k@MWOQQKOQe@_@u@}@kA}@yAwAQWE]E]@cAT{@LYz@oDJUH]fA{El@wBB_@V{@JUH_@D_@b@uArAoFb@wA\\}At@sCP}@Tu@FYLU|@sDF_@rB}Hd@yBJSP_ANUPMPJLOIaB"
  },
  {
    id: "3e492471-f128-4bea-b540-641e8abf7f3e",
    date: "2026-03-18T11:58:25.000Z",
    title: "Nike Run Club: Wednesday Afternoon Run",
    sportType: "run",
    distance: 4005.2,
    duration: 1367,
    speed: 2.941,
    heartRate: 180.3,
    elevationGain: 34,
    completed: true,
    externalId: "17765833929",
    map: "gugtHmyhRNQ`@oAJURQTMLOf@Y`@a@Zi@d@a@jAeBx@wAL[VsA\\mAv@cCZs@l@cA`@_@NQ`@[b@]x@e@RQRIPQ|@a@PCRMPSv@a@NSt@o@LUTMPDNPPKRDdAbA^b@jA`Af@d@PJd@`@PA\\oAJ}@JYPSp@kARq@R_BJYPIR?THvAGRBPIT@`AQtCOh@?f@NPW?}@FeBNSXs@RwAAa@]{BKWQMSGc@_@_AoBoC{Go@kBOWSQgAq@u@m@OSSMa@a@s@c@{AyAUKe@c@{@[u@g@SGSSc@O}AaAoBeAc@OSC{@BI}@LSPPNUVw@NSXo@`B_Db@kA\\i@Vm@A_@MQ?e@_AkASKw@o@o@q@{AmAQUUKs@y@g@]u@o@OQq@o@a@e@k@WSOs@o@UOy@s@_@c@c@]OSa@WMS?c@Ia@KWMQ@c@D]"
  },
  {
    id: "a9eb492f-831d-4c47-8ac2-87a120c2d72b",
    date: "2026-03-12T12:03:51.000Z",
    title: "Nike Run Club: Thursday Afternoon Run",
    sportType: "run",
    distance: 2859.1,
    duration: 912,
    speed: 3.149,
    heartRate: 179.2,
    elevationGain: 24,
    completed: true,
    externalId: "17696100110",
    map: "iugtHqyhRHYPOX{@LUPQd@WhA_AXg@NK^i@x@wAPSl@_APw@Vw@|@kDVs@d@gACc@QOSKgBiBM]c@_@WGOMQUQMOUgBmBa@Y]i@w@q@IWYqBOOSJSI_A_Ak@_@OUSGSOMUw@m@KUu@u@wAoASMKUUQQKc@a@q@y@G[KaAD]Vy@b@{Bf@qBD]Tw@LSHa@HWPy@l@mBP{@j@uBx@uD`AqDZqAVs@F]|@kDP_AJWR_ALQP}@L]`@qBn@qBp@oCTu@l@uCL_@LYNQR?JUAc@Bc@Gc@]q@?["
  },
  {
    id: "738b3a88-99a0-4d17-830f-2fecdd13f0e8",
    date: "2026-03-08T15:10:36.000Z",
    title: "Nike Run Club: Sunday Afternoon Run",
    sportType: "run",
    distance: 2742.3,
    duration: 800,
    speed: 3.441,
    heartRate: 181.2,
    elevationGain: 16,
    completed: true,
    externalId: "17650891215",
    map: "stgtHkyhRNy@H[Zq@b@IJWPGt@y@PY`@a@h@{@L[`AuAd@mAPu@JWTy@F[h@kBx@gB_@m@OKQUQMq@o@sCsCg@[QOgBsBSOa@a@q@_AIYDa@A]QSSDSGOSc@]OSSISQy@s@OUe@]MW{CsCaAw@OUSGq@_AK_@G_@?_@TqAJY~@eEDc@N[n@wBh@}BVsAVw@N}@L]R_AVu@VuAL]Jc@`@oAn@mCL[Z}ARw@LYj@sCNQB]NQb@qBZoAN_ALUD]d@{A`@qBJUv@iCLUPLNMAe@I}@"
  },
  {
    id: "618d1d69-01af-47f4-8f84-1d284ec3b3d3",
    date: "2026-03-04T12:04:30.000Z",
    title: "Nike Run Club: Wednesday Afternoon Run",
    sportType: "run",
    distance: 4007.3,
    duration: 1419,
    speed: 2.85,
    heartRate: 186.5,
    elevationGain: 25,
    completed: true,
    externalId: "17599834090",
    map: "isgtHc}hRLYTEJ]v@]TGPOJWPSRKVo@NUZq@Xe@RQRGNNJVRLn@z@v@t@Zf@T?PL^b@RNLTPPPHPPXj@NLJTPR|@|Ad@LRKJSH_@\\o@Ru@Xm@|@aC`A}BJ[b@kADY\\o@~@uBpAkDLSXs@X{@Ry@h@oCb@kAXm@RUTy@NaAB]TIT@f@HRCPQ`AQ|@MRITEf@@VAVBf@EPFPGVAb@LPMD{AH_Ad@oAR}AWuBSs@OOg@U_@e@KUq@aB[q@s@mBg@gAe@oASq@MUQQUKOQSIu@m@e@[QQe@]{A{ASOe@QQWSGQOu@g@QQgCoAm@Q_@c@i@Q{@g@_AUe@?QDCa@K]LQd@?p@aBH]PQNW|ByELYH[LSG_@MQBg@a@a@gA}@MQSKOUeAcAUKu@k@KU_@WOQc@[QUSK_@a@OSSMw@u@c@Wu@k@eAaAw@o@MUQKs@m@OWOO?e@a@oA"
  },
  {
    id: "7dd8b9b5-a59f-40c5-b460-ff4aa728c40b",
    date: "2026-02-22T12:35:45.000Z",
    title: "Nike Run Club: Sunday Afternoon Run",
    sportType: "run",
    distance: 6069.7,
    duration: 2485,
    speed: 2.86,
    heartRate: 181.2,
    elevationGain: 46,
    completed: true,
    externalId: "17483594040",
    map: "gmgtH_pmRPLLXPJGv@~@nA~ArAb@b@\\d@b@TFXD\\LRb@Pt@j@PT~AnA^b@tAlA`@b@jA|@vAtAb@\\r@p@D\\OPWn@kAtBaA~BOPg@pAm@jAGb@OVOP{@n@OLE^H\\J|@H\\Rt@NZNx@`@lALRtA~@A`@c@rB?^N`BBbDJ|@NXd@XFZCb@Mb@Wp@i@tBLVRNLPTL`@b@TFNTf@^`@`@TJx@l@NNLREZOVKZeAv@MRs@h@cA~@MTQHqCtBiAh@SNSHOPqAt@QPOHy@p@_ArAw@hCU|@MX_@tAQZI\\wBtDo@z@MXyAnAcChLA_@D]@]L{@D}Af@cB^a@JUPINQTGNUr@o@LW`@_@l@}@JY|@sAVk@HWF]XoAHY\\y@P{@Vq@j@aAbAgAdA_Ad@SPQb@WPOjAg@TIhAu@bAaA\\c@f@YNQTu@hAw@b@_@LURMFc@I[_@i@_@_@UMOQw@m@SK_@a@SKa@_@c@m@A_@D]`@kANw@JWCa@e@e@OUG_@E]CaBEy@OwAB]f@mC?]MSSK_AmAG[a@kAg@mBGa@Us@Aa@t@m@d@c@B_AH[P@RAXq@LSPs@tAaCHYr@aBZo@NSJ]KYOO?e@IWcBqAc@e@SOKUi@Ya@e@g@a@e@g@e@]_@g@QKMQOKa@]QUQQy@g@w@o@SKMOSMSG]o@OO"
  }
];
